### GET /members
GET https://2hfpxnawm7.execute-api.us-west-1.amazonaws.com/members
Authorization: 123

### POST /members
POST https://2hfpxnawm7.execute-api.us-west-1.amazonaws.com/members
Authorization: 123
Content-Type: application/json

{
    "username": "jluce",
    "email": "jluce@test.com",
    "name": "Jason"
}

### GET /members/{memberId}
GET https://2hfpxnawm7.execute-api.us-west-1.amazonaws.com/members/f697d05a-8e17-4d6c-ad66-57efd53aa524
Authorization: 123

### PUT /members/{memberId}
PUT https://2hfpxnawm7.execute-api.us-west-1.amazonaws.com/members/f697d05a-8e17-4d6c-ad66-57efd53aa524
Authorization: 123
Content-Type: application/json

{
    "description": "nice",
    "name": "name"
}

### GET /members/{memberId}/projects
GET https://2hfpxnawm7.execute-api.us-west-1.amazonaws.com/members/f697d05a-8e17-4d6c-ad66-57efd53aa524/projects
Authorization: 123

### POST /members/{memberId}/projects
POST https://2hfpxnawm7.execute-api.us-west-1.amazonaws.com/members/f697d05a-8e17-4d6c-ad66-57efd53aa524/projects
Authorization: 123
Content-Type: application/json

{
    "name": "ticketable"
}